version: '3.9'
services:
  heartbeat-client-1:
    image: luisnaldo7/heartbeat-client:latest
    container_name: 'client-1'
    environment:
      - HEARTBEAT_CLIENT_ID=ede88b30-1ba0-431a-9775-acfdf2ac0f57
      - HEARTBEAT_CLIENT_INTERVAL=3
      - HEARTBEAT_SERVER_BASE_URL=http://heartbeat-server:3000
    depends_on:
      heartbeat-server:
        condition: service_started

  heartbeat-client-2:
    image: luisnaldo7/heartbeat-client:latest
    container_name: 'client-2'
    environment:
      - HEARTBEAT_CLIENT_ID=2d15c391-6646-44f3-8ed7-604ab60cddb5
      - HEARTBEAT_CLIENT_INTERVAL=15
      - HEARTBEAT_SERVER_BASE_URL=http://heartbeat-server:3000
    depends_on:
      heartbeat-server:
        condition: service_started

  heartbeat-server:
    image: luisnaldo7/heartbeat-server:latest
    container_name: 'server'
    environment:
      - HEARTBEAT_SERVER_PORT=3000
      - TYPEORM_CONNECTION=mysql
      - TYPEORM_HOST=db
      - TYPEORM_PORT=3306
      - TYPEORM_USERNAME=heartbeat
      - TYPEORM_PASSWORD=password
      - TYPEORM_DATABASE=heartbeat
      - TYPEORM_SYNCHRONIZE=false
      - TYPEORM_LOGGING=false
      - TYPEORM_ENTITIES=dist/**/*.entity.js
    ports:
      - '3000:3000'
    depends_on:
      database:
        condition: service_started

  heartbeat-alert:
    image: luisnaldo7/heartbeat-alert:latest
    container_name: 'alert'
    restart: always
    environment:
      - TYPEORM_CONNECTION=mysql
      - TYPEORM_HOST=db
      - TYPEORM_PORT=3306
      - TYPEORM_USERNAME=heartbeat
      - TYPEORM_PASSWORD=password
      - TYPEORM_DATABASE=heartbeat
      - TYPEORM_SYNCHRONIZE=false
      - TYPEORM_LOGGING=false
      - TYPEORM_ENTITIES=dist/**/*.entity.js
      - MAIL_ENABLED=$MAIL_ENABLED
      - MAIL_HOST=$MAIL_HOST
      - MAIL_PORT=$MAIL_PORT
      - MAIL_FROM=$MAIL_FROM
      - MAIL_PASSWORD=$MAIL_PASSWORD
      - MAIL_TLS=$MAIL_TLS
      - MAIL_TO=$MAIL_TO
      - MAIL_SUBJECT=$MAIL_SUBJECT
      - DISCORD_ENABLED=$DISCORD_ENABLED
      - DISCORD_WEBHOOK_CLIENT_ID=$DISCORD_WEBHOOK_CLIENT_ID
      - DISCORD_WEBHOOK_CLIENT_TOKEN=$DISCORD_WEBHOOK_CLIENT_TOKEN
      - HEARTBEAT_DASHBOARD_URL=$HEARTBEAT_DASHBOARD_URL
    depends_on:
      database:
        condition: service_started

  heartbeat-dashboard:
    image: luisnaldo7/heartbeat-dashboard:latest
    container_name: 'dashboard'
    ports:
      - '80:3001'
    depends_on:
      heartbeat-server:
        condition: service_started

  database:
    image: mysql:8.0.27
    container_name: 'db'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: heartbeat
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: heartbeat
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
